#pragma once
const char* vertex_shader_image = "#version 450 core\n"
    "\n"
    "layout(location = 0) in vec2 pos;\n"
    "layout(location = 1) in vec2 uv;\n"
    "layout(location = 2) in float ang;\n"
    "layout(location = 3) in vec2 rot_p;\n"
    "uniform mat4 projection;\n"
    "out vec2 tex_coord;\n"
    "void main(){\n"
    "    //doing the rotation before conversion causes warpage\n"
    "    vec2 p = (projection * vec4(pos.x, pos.y, 0.0, 1.0)).xy;\n"
    "    vec2 rot = (projection * vec4(rot_p.x, rot_p.y, 0.0, 1.0)).xy;\n"
    "    vec2 pre = p - rot;\n"
    "    pre = vec2(pre.x*cos(ang)-pre.y*sin(ang), pre.y*cos(ang) + pre.x*sin(ang));\n"
    "    pre = pre + rot;\n"
    "    p = pre;\n"
    "    tex_coord = uv;\n"
    "    gl_Position = vec4(p.x, p.y, 0.0, 1.0);\n"
    "}\n"
    "";
const char* fragment_shader_image = "#version 450 core\n"
    "out vec4 color;\n"
    "in vec2 tex_coord;\n"
    "uniform sampler2D mtexture;\n"
    "void main(){\n"
    "    color = texture(mtexture, tex_coord);\n"
    "}";

const char* vertex_shader_grayscale = "#version 450 core\n"
    "\n"
    "layout(location = 0) in vec2 pos;\n"
    "layout(location = 1) in vec2 uv;\n"
    "layout(location = 2) in float ang;\n"
    "layout(location = 3) in vec2 rot_p;\n"
    "uniform mat4 projection;\n"
    "out vec2 tex_coord;\n"
    "void main(){\n"
    "    //doing the rotation before conversion causes warpage\n"
    "    vec2 p = (projection * vec4(pos.x, pos.y, 0.0, 1.0)).xy;\n"
    "    vec2 rot = (projection * vec4(rot_p.x, rot_p.y, 0.0, 1.0)).xy;\n"
    "    vec2 pre = p - rot;\n"
    "    pre = vec2(pre.x*cos(ang)-pre.y*sin(ang), pre.y*cos(ang) + pre.x*sin(ang));\n"
    "    pre = pre + rot;\n"
    "    p = pre;\n"
    "    tex_coord = uv;\n"
    "    gl_Position = vec4(p.x, p.y, 0.0, 1.0);\n"
    "}\n"
    "";
const char* fragment_shader_grayscale = "#version 450 core\n"
    "out vec4 color;\n"
    "in vec2 tex_coord;\n"
    "uniform sampler2D mtexture;\n"
    "uniform bool withAlpha;"
    "void main(){\n"
    "    vec4 texcolor = texture(mtexture, tex_coord);\n"
    "    if(withAlpha) {\n"
    "      color = vec4(texcolor.r, texcolor.r, texcolor.r, texcolor.g);\n"
    "    } else {\n"
    "    color = vec4(texcolor.r, texcolor.r, texcolor.r, texcolor.a);\n"
    "    }\n"
    "}";