#pragma once
const char* triangle_vertex ="#version 450 core\n"
    "\n"
    "layout(location = 0) in vec2 pos;\n"
    "uniform mat4 projection;\n"
    "\n"
    "void main(){\n"
    "    gl_Position = projection * vec4(pos.x, pos.y, 0.0, 1.0);\n"
    "}\n"
    "";
const char* triangle_fragment = "#version 450 core\n"
    "out vec4 color;\n"
    "uniform vec4 set_color;\n"
    "void main(){\n"
    "    color = set_color;\n"
    "}";
const char* point_vertex = "#version 450 core\n"
    "\n"
    "layout(location = 0) in vec2 pos;\n"
    "uniform mat4 projection;\n"
    "uniform float point_size;\n"
    "\n"
    "void main(){\n"
    "    gl_Position = projection * vec4(pos.x, pos.y, 0.0, 1.0);\n"
    "    gl_PointSize = point_size;\n"
    "}\n"
    "";
const char* point_fragment = "#version 450 core\n"
    "out vec4 color;\n"
    "uniform vec4 set_color;\n"
    "void main(){\n"
    "    color = set_color;\n"
    "}";
const char* line_vertex = "#version 450 core\n"
    "\n"
    "layout(location = 0) in vec2 pos;\n"
    "uniform mat4 projection;\n"
    "void main(){\n"
    "    gl_Position = projection * vec4(pos.x, pos.y, 0.0, 1.0);\n"
    "}\n"
    "";
const char* line_fragment = "#version 450 core\n"
    "out vec4 color;\n"
    "uniform vec4 set_color;\n"
    "void main(){\n"
    "    color = set_color;\n"
    "}";