#pragma once
const char* vertex_shader_image = "#version 450 core\n"
    "\n"
    "layout(location = 0) in vec2 pos;\n"
    "layout(location = 1) in vec2 uv;\n"
    "layout(location = 2) in float ang;\n"
    "layout(location = 3) in vec2 rot_p;\n"
    "layout(location = 4) in uint tex_u;\n"
    "uniform mat4 projection;\n"
    "uniform mat4 view;\n"
    "out vec2 tex_coord;\n"
    "flat out uint tex_unit;\n"
    "void main(){\n"
    "    //doing the rotation before conversion causes warpage\n"
    "    vec2 p = (projection * view * vec4(pos.x, pos.y, 0.0, 1.0)).xy;\n"
    "    vec2 rot = (projection * view * vec4(rot_p.x, rot_p.y, 0.0, 1.0)).xy;\n"
    "    vec2 pre = p - rot;\n"
    "    pre = vec2(pre.x*cos(ang)-pre.y*sin(ang), pre.y*cos(ang) + pre.x*sin(ang));\n"
    "    pre = pre + rot;\n"
    "    p = pre;\n"
    "    tex_coord = uv;\n"
    "    tex_unit = tex_u;\n"
    "    gl_Position = vec4(p.x, p.y, 0.0, 1.0);\n"
    "}\n"
    "";
const char* fragment_shader_image = "#version 450 core\n"
    "#extension GL_ARB_bindless_texture : require\n"
    "out vec4 color;\n"
    "in vec2 tex_coord;\n"
    "flat in uint tex_unit;\n"
    "layout(binding = 0, std430) readonly buffer ssbo1 {\n"
    "    sampler2D textures[];\n"
    "};\n"
    "void main(){\n"
    "    color = texture(textures[tex_unit], tex_coord);\n"
    "}";

const char* vertex_shader_texture_unit_image = "#version 330 core\n"
    "layout(location = 0) in vec2 pos;\n"
    "layout(location = 1) in vec2 uv;\n"
    "layout(location = 2) in float ang;\n"
    "layout(location = 3) in vec2 rot_p;\n"
    "layout(location = 4) in uint tex_u;\n"
    "uniform mat4 projection;\n"
    "uniform mat4 view;\n"
    "out vec2 tex_coord;\n"
    "flat out uint tex_unit;\n"
    "void main(){\n"
    "    vec2 p = (projection * view * vec4(pos, 0.0, 1.0)).xy;\n"
    "    vec2 rot = (projection * view * vec4(rot_p, 0.0, 1.0)).xy;\n"
    "    vec2 pre = p - rot;\n"
    "    pre = vec2(pre.x*cos(ang)-pre.y*sin(ang), pre.y*cos(ang)+pre.x*sin(ang));\n"
    "    p = pre + rot;\n"
    "    tex_coord = uv;\n"
    "    tex_unit = tex_u;\n"
    "    gl_Position = vec4(p, 0.0, 1.0);\n"
    "}\n";

const char* fragment_shader_texture_unit_image = "#version 330 core\n"
    "out vec4 color;\n"
    "in vec2 tex_coord;\n"
    "flat in uint tex_unit;\n"
    "uniform sampler2D tex_array[TEXTURE_UNIT];\n"
    "void main(){\n"
    "    color = vec4(0.0);\n"
    "    switch(tex_unit) {\n"
    "        TEXTURE_SWITCH tex_array tex_coord\n"
    "    }\n"
    "}\n";

const char* vertex_shader_grayscale = "#version 450 core\n"
    "\n"
    "layout(location = 0) in vec2 pos;\n"
    "layout(location = 1) in vec2 uv;\n"
    "layout(location = 2) in float ang;\n"
    "layout(location = 3) in vec2 rot_p;\n"
    "layout(location = 4) in uint tex_u;\n"
    "uniform mat4 projection;\n"
    "uniform mat4 view;\n"
    "out vec2 tex_coord;\n"
    "flat out uint tex_unit;\n"
    "void main(){\n"
    "    //doing the rotation before conversion causes warpage\n"
    "    vec2 p = (projection * view * vec4(pos.x, pos.y, 0.0, 1.0)).xy;\n"
    "    vec2 rot = (projection * view * vec4(rot_p.x, rot_p.y, 0.0, 1.0)).xy;\n"
    "    vec2 pre = p - rot;\n"
    "    pre = vec2(pre.x*cos(ang)-pre.y*sin(ang), pre.y*cos(ang) + pre.x*sin(ang));\n"
    "    pre = pre + rot;\n"
    "    p = pre;\n"
    "    tex_coord = uv;\n"
    "    tex_unit = tex_u;\n"
    "    gl_Position = vec4(p.x, p.y, 0.0, 1.0);\n"
    "}\n"
    "";
const char* fragment_shader_grayscale = "#version 450 core\n"
    "#extension GL_ARB_bindless_texture : require\n"
    "out vec4 color;\n"
    "in vec2 tex_coord;\n"
    "flat in uint tex_unit;\n"
    "layout(binding = 0, std430) readonly buffer ssbo1 {\n"
    "    sampler2D textures[];\n"
    "};\n"
    "uniform bool withAlpha;"
    "void main(){\n"
    "    vec4 texcolor = texture(textures[tex_unit], tex_coord);\n"
    "    if(withAlpha) {\n"
    "      color = vec4(texcolor.r, texcolor.r, texcolor.r, texcolor.g);\n"
    "    } else {\n"
    "      color = vec4(texcolor.r, texcolor.r, texcolor.r, texcolor.a);\n"
    "    }\n"
    "}";