#pragma once

const char* three_dee_renderer_vertex = "#version 450 core\n"
    "\n"
    "layout(location = 0) in vec3 pos;\n"
    "layout(location = 1) in vec2 uv;\n"
    "layout(location = 2) in uint model_matrice;\n"
    "layout(location = 3) in uint texture_unit;\n"
    "uniform mat4 view;\n"
    "uniform mat4 projection;\n"
    "layout(std430, binding = 0) readonly buffer ssbo1\n"
    "{\n"
    "   mat4 modelMatrices[];\n"
    "};\n"
    "out vec2 uv_c;\n"
    "flat out uint tex_unit;\n"
    "void main(){\n"
    "   tex_unit = texture_unit;\n"
    "   uv_c = uv;\n"
    "   mat4 model = mat4(1.0);"
    "   if (model_matrice != -1) {\n"
    "       model = transpose(modelMatrices[model_matrice]);\n"
    "   }\n"
    "   gl_Position = projection * view * model * vec4(pos, 1.0);\n"
    "}\n"
    "";


const char* three_dee_renderer_fragment = "#version 450 core\n"
    "#extension GL_ARB_bindless_texture : require\n"
    "#define UINT32_MAX 0xffffffffu\n"
    "in vec2 uv_c;\n"
    "out vec4 color;\n"
    "uniform vec4 set_color;\n"
    "flat in uint tex_unit;\n"
    "layout(std430, binding = 1) readonly buffer ssbo2\n"
    "{\n"
    "   sampler2D textures[];\n"
    "};\n"
    "void main(){\n"
    "    if (tex_unit == UINT32_MAX) {\n"
    "        color = set_color;\n"
    "    } else {\n"
    "        color = texture(textures[tex_unit], uv_c);\n"
    "    }\n"
    "}";

const char* three_dee_renderer_fragment_texture_unit = "#version 430 core\n"
    "#define UINT32_MAX 0xffffffffu\n"
    "in vec2 uv_c;\n"
    "out vec4 color;\n"
    "uniform vec4 set_color;\n"
    "flat in uint tex_unit;\n"
    "uniform sampler2D tex_array[TEXTURE_UNIT];\n"
    "void main(){\n"
    "    if (tex_unit == UINT32_MAX) {\n"
    "        color = set_color;\n"
    "    } else {\n"
    "        color = vec4(0.0);\n"
    "        switch (tex_unit) {\n"
    "            TEXTURE_SWITCH tex_array uv_c\n"
    "        }\n"
    "    }\n"
    "}";

const char* instance_renderer_vertex = "#version 450 core\n"
"\n"
"#extension GL_ARB_shader_draw_parameters : require\n"
"\n"
"layout(location = 0) in vec3 pos;\n"
"layout(location = 1) in vec2 uv;\n"
"uniform mat4 view;\n"
"uniform mat4 projection;\n"
"layout(std430, binding = 0) readonly buffer ssbo1\n"
"{\n"
"   mat4 modelMatrices[];\n"
"};\n"
"layout(std430, binding = 2) readonly buffer texture_ssbo_buffer\n"
"{\n"
"    uint textureLayers[];\n"
"};\n"
"out vec2 uv_c;\n"
"flat out uint tex_unit;\n"
"void main(){\n"
"   uv_c = uv;\n"
"   uint model_index = gl_BaseInstanceARB + gl_InstanceID;\n"
"   tex_unit = textureLayers[model_index];\n"
"   mat4 model = transpose(modelMatrices[model_index]);\n"
"   gl_Position = projection * view * model * vec4(pos, 1.0);\n"
"}\n";