const char* three_dee_renderer_vertex = "#version 450 core\n"
    "\n"
    "layout(location = 0) in vec3 pos;\n"
    "layout(location = 1) in vec2 uv;\n"
    "layout(location = 2) in uint model_matrice;\n"
    "layout(location = 3) in uint texture_unit;\n"
    "uniform mat4 view;\n"
    "uniform mat4 projection;\n"
    "layout(std430, binding = 1) readonly buffer ssbo1\n"
    "{\n"
    "   mat4 modelMatrices[];\n"
    "};\n"
    "out vec2 uv_c;\n"
    "flat out uint tex_unit;\n"
    "void main(){\n"
    "   tex_unit = texture_unit;\n"
    "   uv_c = uv;\n"
    "   mat4 model = mat4(1.0);"
    "   if (model_matrice != -1) {\n"
    "       model = transpose(modelMatrices[model_matrice]);\n"
    "   }\n"
    "   gl_Position = projection * view * model * vec4(pos, 1.0);\n"
    "}\n"
    "";


const char* three_dee_renderer_fragment = "#version 450 core\n"
    "in vec2 uv_c;\n"
    "out vec4 color;\n"
    "uniform vec4 set_color;\n"
    "flat in uint tex_unit;\n"
    "uniform sampler2D textures[TEXTURE_UNIT];\n"
    "void main(){\n"
    "    if (tex_unit < 1000u) {\n"
    "       color = texture(textures[tex_unit], uv_c);\n"
    "    } else {\n"
    "       color = set_color;\n"
    "    }\n"
    "}";