
const char* wireframe_vertex_shader = "#version 450 core\n"
    "\n"
    "layout(location = 0) in vec3 pos;\n"
    "layout(location = 1) in float angle;\n"
    "layout(location = 2) in vec3 rot_pot;\n"
    "layout(location = 3) in uint axis;\n"
    "void main(){\n"
    "   vec3 p_out = pos - rot_pot;\n"
    "   switch(axis) {\n"
    "       case 0:\n"
    "       {\n"
    "           float oy = p_out.y, oz = p_out.z;\n"
    "           p_out.y = oy * cos(angle) - oz * sin(angle);\n"
    "           p_out.z = oy * sin(angle) + oz * cos(angle);\n"
    "       }\n"
    "       break;"
    "       case 1:\n"
    "       {\n"
    "           float ox = p_out.x, oz = p_out.z;\n"
    "           p_out.x = ox * cos(angle) + oz * sin(angle);\n"
    "           p_out.z = -ox * sin(angle) + oz * cos(angle);\n"
    "       }\n"
    "       break;"
    "       case 2:\n"
    "       {\n"
    "           float ox = p_out.x, oy = p_out.y;\n"
    "           p_out.x = ox * cos(angle) - oy * sin(angle);\n"
    "           p_out.y = ox * sin(angle) + oy * cos(angle);\n"
    "       }\n"
    "       break;"
    "   }\n"
    "   p_out = p_out + rot_pot;\n"
    "   vec2 p = vec2(p_out.x / p_out.z, p_out.y / p_out.z);\n"
    "   gl_Position = vec4(p.x, p.y, 0.0, 1.0);\n"
    "}\n"
    "";
const char* wireframe_fragment_shader = "#version 450 core\n"
    "out vec4 color;\n"
    "uniform vec4 set_color;\n"
    "void main(){\n"
    "    color = set_color;\n"
    "}";