#include "backend.hpp"
#include <cstdlib>
#include <memory>


std::function<void(uint32_t, uint32_t)> globalResize;
bool globalCapture = false;

void gore::g_window::setMouseMoveFunction (std::function<void()> function) {
	this->mouseMove = function;
}

#if defined(_WIN32)
bool globalMaintainViewport = false;
LRESULT CALLBACK WindowProc(HWND hwnd, UINT msg, WPARAM wparam, LPARAM lparam) {
	switch (msg) {
	case WM_PAINT:

		break;
	case WM_SIZE:
		{
			uint32_t width = LOWORD(lparam);
			uint32_t height = HIWORD(lparam);
			if (!globalMaintainViewport) {
				glViewport(0, 0, width, height);
			}
			if (globalResize) {
				globalResize(width, height);
			}
			if (globalCapture) {
				RECT clRect;
				GetClientRect(hwnd, &clRect);
				POINT tl = { clRect.left, clRect.top };
				POINT br = { clRect.right, clRect.bottom };
				ClientToScreen(hwnd, &tl);
				ClientToScreen(hwnd, &br);
				RECT clip = { tl.x, tl.y, br.x, br.y };
				ClipCursor(&clip);
			}
		}
		break;
	case WM_CLOSE:
		DestroyWindow(hwnd);
		break;
	case WM_DESTROY:
		PostQuitMessage(0);
		return 0;
	}
	return DefWindowProc(hwnd, msg, wparam, lparam);
}
#endif

gore::g_window::~g_window() {
	//has to be same class name
	#if defined(_WIN32)
	UnregisterClass("GENG", r_display);
	#endif
	#if defined(__unix__)
    XDestroyWindow(r_display, m_hwnd);
	#endif
}

bool gore::g_window::ProcessMessage() {
	#if defined(_WIN32)
	MSG msg = {};

	while (PeekMessage(&msg, nullptr, 0u, 0u, PM_REMOVE)) {
		if (msg.message == WM_QUIT) {
			return false;
		} else if (msg.message == WM_MOUSEMOVE) {
			if (this->warping) {
				// this WM_MOUSEMOVE was generated by our own SetCursorPos; don't
				// feed it back into the callback or we warp (and rotate) forever
				this->warping = false;
			} else {
				if (this->mouseMove) {
					this->mouseMove();
				}
				if (this->center && globalCapture) {
					RECT rect;
					GetClientRect(m_hwnd, &rect);
					POINT center_pt = { rect.right / 2, rect.bottom / 2 };
					ClientToScreen(m_hwnd, &center_pt);
					POINT cur;
					GetCursorPos(&cur);
					if (cur.x != center_pt.x || cur.y != center_pt.y) {
						this->warping = true;
						SetCursorPos(center_pt.x, center_pt.y);
					}
				}
			}
		}
		TranslateMessage(&msg);
		DispatchMessage(&msg);
	}
	#endif
	#if defined(__unix__)
	XEvent event;
        if (XPending(r_display)) {
            XNextEvent(r_display, &event);
			logger->log("event: " + std::to_string(event.type));
			switch (event.type) {
				case DestroyNotify:
					return false;
				case ConfigureNotify:
					if (this->resizeFunction) {
						this->width = event.xconfigure.width;
						this->height = event.xconfigure.height;
						if (!maintainViewport) {
							glViewport(0, 0, width, height);
						}
						this->resizeFunction(width, height);
					}
				break;
				case Expose:
					if (this->resizeFunction) {
						this->width = event.xexpose.width;
						this->height = event.xexpose.height;
						if (!maintainViewport) {
							glViewport(0, 0, width, height);
						}
						this->resizeFunction(width, height);
					}
				break;
				case MotionNotify:
					if (this->mouseMove) {
						this->mouseMove();
					}
					if (this->center && this->captured) {
						unsigned long warp_event_serial = XNextRequest(r_display);
						XWarpPointer(r_display, None, m_hwnd, 0, 0, 0, 0, width/2, height/2);
					}
				break;
			}
		}
	#endif
	return true;
}

bool gore::g_window::updateWindow() {
	#if defined(_WIN32)
	return UpdateWindow(getRawWindow());
	#endif
	#if defined(__unix__)
	return XMapWindow(r_display, m_hwnd);
	#endif
}


bool gore::g_window::swapBuffers() {
	#if defined(_WIN32)
	return SwapBuffers(GetDC(getRawWindow()));
	#endif
	#if defined(__unix__)
	glXSwapBuffers(r_display, m_hwnd);
	return true;
	#endif
}
#if defined(_WIN32)
gore::g_window::g_window(const char* title, RAW_DISPLAY r_display, int h, int w, int x, int y, bool fullscreen, bool maintainViewport, std::shared_ptr<gore::logger> logger)
	: r_display(GetModuleHandle(nullptr))
{
	this->logger = logger;
	this->maintainViewport = maintainViewport;
	globalMaintainViewport = maintainViewport;
	WNDCLASS wnd = {};
	wnd.style = CS_OWNDC | CS_HREDRAW | CS_VREDRAW | CS_DBLCLKS;
	wnd.lpszClassName = "GENG";
	wnd.hInstance = r_display;
	wnd.hIcon = LoadIcon(NULL, IDI_WINLOGO);
	wnd.hCursor = LoadCursor(NULL, IDC_ARROW);
	wnd.hbrBackground = NULL;
	wnd.lpszMenuName = NULL;
	wnd.cbClsExtra = 0;
	wnd.cbWndExtra = 0;
	wnd.lpfnWndProc = WindowProc;

	RegisterClass(&wnd);

	DWORD windStyle = WS_OVERLAPPEDWINDOW | WS_MINIMIZEBOX | WS_SYSMENU;
	height = h;
	width = w;

	RECT rect;
	rect.left = x;
	rect.top = y;
	rect.right = rect.left + width;
	rect.bottom = rect.top + height;

	AdjustWindowRect(&rect, windStyle, false);

	m_hwnd = CreateWindowEx(0, wnd.lpszClassName,
		title,
		windStyle,
		rect.left,
		rect.top,
		rect.right - rect.left,
		rect.bottom - rect.top,
		NULL,
		NULL,
		r_display,
		NULL
	);
}
#endif

#if defined(__unix__)
gore::g_window::g_window(const char* title, RAW_DISPLAY display, int h, int w, int x, int y, bool fullscreen, bool maintainViewport, std::shared_ptr<gore::logger> logger) {
	this->logger = logger;
    if (!display) {
        logger->log("Unable to open X display");
        exit(1);
    }
	this->r_display = display;
	height = h;
	width = w;
	this->maintainViewport = maintainViewport;
    Window root = DefaultRootWindow(display);
	// Choose framebuffer config
	static int visual_attribs[] = {
	GLX_X_RENDERABLE    , True,
	GLX_DRAWABLE_TYPE   , GLX_WINDOW_BIT,
	GLX_RENDER_TYPE     , GLX_RGBA_BIT,
	GLX_X_VISUAL_TYPE   , GLX_TRUE_COLOR,
	GLX_RED_SIZE        , 8,
	GLX_GREEN_SIZE      , 8,
	GLX_BLUE_SIZE       , 8,
	GLX_ALPHA_SIZE      , 8,
	GLX_DEPTH_SIZE      , 24,
	GLX_DOUBLEBUFFER    , True,
	None
	};
	int fbcount;
    GLXFBConfig* fbc = glXChooseFBConfig(r_display, DefaultScreen(r_display), visual_attribs, &fbcount);
    if (!fbc) {
        fprintf(stderr, "Failed to get framebuffer config\n");
        return;
    }

    GLXFBConfig fbconfig = fbc[0];
    XVisualInfo* vi = glXGetVisualFromFBConfig(r_display, fbconfig);

    // Create window
    XSetWindowAttributes swa;
    swa.colormap = XCreateColormap(r_display, RootWindow(r_display, vi->screen), vi->visual, AllocNone);
    swa.event_mask = ExposureMask | KeyPressMask;

    m_hwnd = XCreateWindow(r_display, root, 0, 0, w, h, 0, vi->depth,
                        InputOutput, vi->visual, CWColormap | CWEventMask, &swa);
	if (fullscreen) {
		XWindowAttributes window_attributes;
		XGetWindowAttributes(r_display, root, &window_attributes);
		XResizeWindow(r_display, m_hwnd, window_attributes.width, window_attributes.height);
		Atom wm_state = XInternAtom(r_display, "_NET_WM_STATE" ,False);
		Atom wm_fullscreen = XInternAtom(r_display, "_NET_WM_STATE_FULLSCREEN", False);
		XChangeProperty(r_display, m_hwnd, wm_state, XA_ATOM, 32, PropModeReplace, (unsigned char*)&wm_fullscreen, 1);
	}
	XMapWindow(r_display, m_hwnd);
	XStoreName(r_display, m_hwnd, title);
	XFree(vi);
	XFree(fbc);

}
#endif

int gore::g_window::getWidth() {
	return width;
}
int gore::g_window::getHeight() {
	return height;
}
RAW_WINDOW gore::g_window::getRawWindow() {
	return m_hwnd;
}
RAW_DISPLAY gore::g_window::getRawDisplay() {
	return r_display;
}


void gore::g_window::toggleFullscreen() {
	#if defined(_WIN32)
	DWORD dwStyle = GetWindowLong(m_hwnd, GWL_STYLE);
	MONITORINFO mi = { sizeof(mi) };
	mi.cbSize = sizeof(MONITORINFO);
	
	GetMonitorInfo(MonitorFromWindow(m_hwnd, MONITOR_DEFAULTTONEAREST), &mi);
	if (!fullscreen) {
		SetWindowLongPtr(m_hwnd, GWL_STYLE, dwStyle & ~WS_OVERLAPPEDWINDOW);
		SetWindowPos(m_hwnd, HWND_TOP, mi.rcMonitor.left, mi.rcMonitor.top,
						mi.rcMonitor.right - mi.rcMonitor.left,
						mi.rcMonitor.bottom - mi.rcMonitor.top,
						SWP_NOOWNERZORDER | SWP_FRAMECHANGED);
	} else {
		RECT rect;
		rect.left = (mi.rcMonitor.left + (width/2));
		rect.top = (mi.rcMonitor.top + (height/2));
		rect.right = rect.left + width;
		rect.bottom = rect.top + height;

		AdjustWindowRect(&rect, WS_VISIBLE | WS_OVERLAPPEDWINDOW | WS_SYSMENU, false);
		SetWindowLongPtr(m_hwnd, GWL_STYLE, WS_VISIBLE | WS_OVERLAPPEDWINDOW | WS_MINIMIZEBOX | WS_SYSMENU);
		SetWindowPos(m_hwnd, HWND_TOP, 
				rect.left,
				rect.top,
				rect.right - rect.left,
				rect.bottom - rect.top,
				SWP_NOOWNERZORDER | SWP_FRAMECHANGED);
	}
	#endif
	#if defined(__unix__)
		Atom wm_state = XInternAtom(r_display, "_NET_WM_STATE" ,False);
		Atom fullscreen = XInternAtom(r_display, "_NET_WM_STATE_FULLSCREEN", False);
		XEvent event;
		event.xclient.type = ClientMessage;
		event.xclient.serial = 0;
		event.xclient.send_event = True;
		event.xclient.window = m_hwnd;
		event.xclient.message_type = wm_state;
		event.xclient.format = 32;
		event.xclient.data.l[0] = !this->fullscreen; // 1 for _NET_WM_STATE_ADD
		event.xclient.data.l[1] = fullscreen;
		event.xclient.data.l[2] = 0;
		XSendEvent(r_display, DefaultRootWindow(r_display), False, 
               SubstructureNotifyMask | SubstructureRedirectMask, &event);   
    	XFlush(r_display);
		XMapWindow(r_display, m_hwnd);
	#endif
	this->fullscreen = !this->fullscreen;
}

void gore::g_window::setWindowResize(std::function<void(uint32_t, uint32_t)> func) {
	this->resizeFunction = func;
	globalResize = func;
}

void gore::g_window::captureMouseToggle(bool center){
	#if defined(_WIN32)
	if (!captured) {
		RECT clRect;
		GetClientRect(m_hwnd, &clRect);
		POINT tl = { clRect.left, clRect.top };
		POINT br = { clRect.right, clRect.bottom };
		ClientToScreen(m_hwnd, &tl);
		ClientToScreen(m_hwnd, &br);
		RECT clip = { tl.x, tl.y, br.x, br.y };
		ClipCursor(&clip);
		if (center) {
			// start centered so the first mouse-move delta is zero
			warping = true;
			SetCursorPos((tl.x + br.x) / 2, (tl.y + br.y) / 2);
		}
	} else {
		ClipCursor(NULL);
	}
	#endif
	#if defined(__unix__)
	if (!captured) {
		XGrabPointer(r_display, m_hwnd, True, ButtonPressMask | ButtonReleaseMask | PointerMotionMask, GrabModeAsync, GrabModeAsync, m_hwnd, None, CurrentTime);
		if (center) {
			// start centered so the first mouse-move delta is zero
			XWarpPointer(r_display, None, m_hwnd, 0, 0, 0, 0, width/2, height/2);
		}
	} else {
		XUngrabPointer(r_display, CurrentTime);
	}
	#endif
	captured = !captured;
	globalCapture = captured;
	this->center = center;
}

void gore::g_window::mouseHideToggle() {
	#if defined(_WIN32)
	ShowCursor(!mouseHide);
	#endif
	#if defined(__unix__)
	if (!mouseHide) {
		Cursor invisibleCursor;
		Pixmap blank;
		XColor black;
		static char noData[1] = { 0};

		blank = XCreateBitmapFromData (r_display, m_hwnd, noData, 1, 1);
		invisibleCursor = XCreatePixmapCursor(r_display, blank, blank, &black, &black, 0, 0);
		XDefineCursor(r_display, m_hwnd, invisibleCursor);
		XFreeCursor(r_display, invisibleCursor);
		XFreePixmap(r_display, blank);
	} else {
		XUndefineCursor(r_display, m_hwnd);
	}
	#endif
	mouseHide = !mouseHide;
}


uint32_t gore::g_window::getDPI() {
	#if defined(_WIN32)
		UINT dpi = GetDpiForWindow(m_hwnd);
		return dpi;
	#endif
	#if defined(__unix__)
		Screen* screen = DefaultScreenOfDisplay(r_display);
		int dpi = (int)((WidthOfScreen(screen) * 25.4) / WidthMMOfScreen(screen));
		return dpi;
	#endif
	return 96;
}

void gore::g_window::setMaintainViewport(bool maintainViewport) {
	this->maintainViewport = maintainViewport;
	#if defined(_WIN32)
	globalMaintainViewport = maintainViewport;
	#endif
}

void gore::g_window::setWindowTitle (std::string title) {
	#if defined(_WIN32)
		SetWindowTextA(this->m_hwnd, title.c_str());
	#endif
	#if defined(__unix__)
		XStoreName(this->r_display, this->m_hwnd, title.c_str());
	#endif
}